### ISSUE TITLE
Unsupported shape calculation for operator Dropout

### ISSUE THREAD

**Issue by eraoul** [onnx/onnxmltools#124] opened 2018-08-02 00:38 UTC
I made a new model using keras, and saved it to an .hdf file using a callback during training.

I reloaded the model and tried to convert to an ONNX model:
```
model = keras.models.load_model(filename)
winml_onnx_model = onnxmltools.convert_keras(model)
```

convert_keras throws an error here. Any idea what I might be doing wrong? I'm on Windows 10, python 3.6.2, Tensorflow 1.8, Keras 2.1.5, onnxmltools 1.2.0.0116, winmltools 1.2.0.0725

The model uses the following operators (but the error seems to be due to the Dropout layer):

Activation, Dropout, BatchNormalization, Convolution2D, MaxPooling2D, GlobalAveragePooling2D

If I do model.summary() everything seems fine with my model. Batch size is always specified as "None" in the model summary, so I wonder if there's some issue with how to deal with batch size in the ONNx conversion (this is my first time making an ONNX model)

Thanks!

UPDATE: This simple model gives the same error. I also tried specifying the batch_input_shape explicitly to just allow 1 item in the batch, and it didn't change anything:

```
model2 = Sequential()
model2.add(Dense(50, batch_input_shape=[1, 5]))
model2.add(Dropout(0.5))
winml_onnx_model2 = onnxmltools.convert_keras(model2)

```

Error below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-da007af6c51d> in <module>()
----> 1 winml_onnx_model = onnxmltools.convert_keras(model)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\main.py in convert_keras(model, name, initial_types, doc_string, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
     36     from .keras.convert import convert
     37     return convert(model, name, initial_types,
---> 38                    doc_string, targeted_onnx, custom_conversion_functions, custom_shape_calculators)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\keras\convert.py in convert(model, name, initial_types, doc_string, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
     40     topology = parse_keras(model, initial_types, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
     41 
---> 42     topology.compile()
     43 
     44     if name is None:

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\common\_topology.py in compile(self)
    607         self._resolve_duplicates()
    608         self._fix_shapes()
--> 609         self._infer_all_types()
    610         self._check_structure()
    611 

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\common\_topology.py in _infer_all_types(self)
    493                 pass  # in Keras converter, the shape calculator can be optional.
    494             else:
--> 495                 operator.infer_types()
    496 
    497     def _resolve_duplicates(self):

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\common\_topology.py in infer_types(self)
     95     def infer_types(self):
     96         # Invoke a core inference function
---> 97         _registration.get_shape_calculator(self.type)(self)
     98 
     99 

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\onnxmltools\convert\common\_registration.py in get_shape_calculator(operator_name)
     66     '''
     67     if operator_name not in _shape_calculator_pool:
---> 68         raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
     69     return _shape_calculator_pool[operator_name]

ValueError: Unsupported shape calculation for operator <class 'keras.layers.core.Dropout'>
```

**Comment by wenbingl** [comment] 2018-08-02 04:33
I can this is a bug in the converter. You can have a PR for that, or we will fix it soon.

**Comment by wschin** [comment] 2018-08-02 05:01
I think it's a bug caused by a missing converter/shape calculator for Dropout layer. To fix this problem, we need to add a converter (example is [here](https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/keras/operator_converters/Dense.py)) and a shape calculator (example is [here](https://github.com/onnx/onnxmltools/blob/708d3091084da1acf42cf058161017e1152fa337/onnxmltools/convert/keras/shape_calculators/Lazy.py#L54)).
@wenbingl , @duli2012 , could you find someone to fix this problem? It's quite simple because Dropout is basically an identity operator in prediction phase.

**Comment by wschin** [comment] 2018-08-02 05:04
@eraoul , using `None` for batch size is fine for runtime. It's officially supported by ONNX standard. Note that `None` means a variable-length dimension (think about speed recognition, the length of a sentence is always not deterministic)

**Comment by eraoul** [comment] 2018-08-02 15:39
Thanks for the quick feedback. I'll be looking forward to the fix!

BTW is there a list of supported operations somewhere to track this sort of thing? I expected Dropout to be supported; perhaps there are other ops that should be checked on as well to avoid similar errors?

**Comment by wschin** [comment] 2018-08-02 15:47
@eraoul , good point! We should document the list down. @wenbingl , @duli2012 , could you add a doc string into [convert of Keras](https://github.com/onnx/onnxmltools/blob/708d3091084da1acf42cf058161017e1152fa337/onnxmltools/convert/keras/convert.py#L19) (like what we did for [sklearn](https://github.com/onnx/onnxmltools/blob/708d3091084da1acf42cf058161017e1152fa337/onnxmltools/convert/sklearn/convert.py#L23)).

**Comment by eraoul** [comment] 2018-08-02 20:06
Just for my planning, can you give me an estimate of when your team might be able to fix this Dropout bug? (e.g., days or weeks?) Also, will I need to re-build onnxmltools from source when this goes in or do you update the pip repo frequently?

Thanks in advance for the help!

**Comment by wenbingl** [comment] 2018-08-03 18:22
We will fix it in the next week.

**Comment by eraoul** [comment] 2018-08-03 18:26
Thanks Wenbing, that's great news.  Does this mean I'll need to build from
source after the fix, or will it be fixed in the pip package on pypi?

**Comment by eraoul** [comment] 2018-08-03 23:26
Perfect -- thanks!  Will be looking for the update next week.

Cheers,
Eric

**Comment by wschin** [comment] 2018-08-07 23:17
Hi @eraoul, @wenbingl just merge a fix for supporting Dropout. Would you mind to try it again? Thanks.

**Comment by eraoul** [comment] 2018-08-15 01:37
Thanks so much Wei-Sheng and Wenbing -- the converter works for me now.
Really appreciate the quick fix!

**Comment by wschin** [comment] 2018-08-17 19:51
Thanks. Let me close this issue.

**Closed by wschin** 2018-08-17 19:51 UTC
Labels: bug, enhancement
